# Generated by Django 3.0.3 on 2020-02-11 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Footwear', 'Footwear'), ('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Accessories', 'Accessories')], default='Footwear', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('Mint', 'Mint'), ('Good', 'Good'), ('Fair', 'Fair'), ('Character Flawed', 'Character Flawed')], default='Mint', max_length=100)),
                ('topsize', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'L'), ('XXL', 'XXL'), ('OTHER', 'OTHER')], default='M', max_length=100)),
                ('bottomsize', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'L'), ('XXL', 'XXL'), ('OTHER', 'OTHER')], default='M', max_length=100)),
                ('shoesize', models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], default='10', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
