# Generated by Django 3.0.3 on 2020-02-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_auto_20200211_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user_id',
            new_name='user',
        ),
    ]
