# Generated by Django 3.0.3 on 2020-02-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_auto_20200211_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
